#pragma once

#define MATRIX_MASKED
#define BOOTMAGIC_LITE_ROW 0
#define BOOTMAGIC_LITE_COLUMN 8
#define DYNAMIC_KEYMAP_LAYER_COUNT 7
#define PERMISSIVE_HOLD

#define VIAL_KEYBOARD_UID {0xCE, 0xB5, 0x38, 0x98, 0xC3, 0xB3, 0xBF, 0xC7}

#define VIAL_UNLOCK_COMBO_ROWS { 0 }
#define VIAL_UNLOCK_COMBO_COLS { 8 }
